# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
