# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plugins',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=50)),
                ('BugID', models.CharField(max_length=20)),
                ('RuleString', models.CharField(max_length=200)),
                ('RCA', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='temp',
        ),
    ]
